version: '3'
services:
  user_auth_service:
    container_name: 'workout-app-user-service'
    build: ./user-auth-service
    restart: always
    ports:
      - '8090:8090'
    depends_on:
      - mongo
  workout_data_service:
    container_name: 'workout-app-data-service'
    build: './workout-data-service'
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - mongo
  client:
    container_name: 'workout-app-client'
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - user_auth_service
  mongo:
    image: 'mongo'
    container_name: 'workout-app-mongo'
    ports:
      - '27017:27017'
